DROP TABLE REPORT;
DROP TABLE QNA;
DROP TABLE FAQ;
DROP TABLE NOTICE;
DROP TABLE MEMBER_GRADE;
DROP TABLE REVIEW_UP;
DROP TABLE FAVORITES;
DROP TABLE MENU;
DROP TABLE REVIEW;
DROP TABLE MEMBER;
DROP TABLE ATTACHMENT;
DROP TABLE UPDATE_REST;
DROP TABLE NO_MEMBER;
DROP TABLE SITE_INFO;
DROP TABLE OPEN_TIME;
DROP TABLE RESTAURANT;
DROP TABLE TV;
DROP TABLE FOOD_CATEGORY;


DROP SEQUENCE SEQ_NNO;
DROP SEQUENCE SEQ_QNO;
DROP SEQUENCE SEQ_FAQNO; 
DROP SEQUENCE SEQ_MNO; 
DROP SEQUENCE SEQ_REPNO; 
DROP SEQUENCE SEQ_GNO; 
DROP SEQUENCE SEQ_REVNO;
DROP SEQUENCE SEQ_RESTNO; 
DROP SEQUENCE SEQ_FNO; 
DROP SEQUENCE SEQ_CNO; 
DROP SEQUENCE SEQ_UNO; 


-------------------------------- CREATE TABLE ----------------------------------
-------------------------------- 주원 테이블 -------------------------------------

CREATE TABLE MEMBER(
    MEM_NO NUMBER PRIMARY KEY,
    MEM_GRADE VARCHAR2(20) NOT NULL,
    MEM_ID VARCHAR2(20) NOT NULL,
    MEM_PWD VARCHAR2(20) NOT NULL,
    MEM_NAME VARCHAR2(20) NOT NULL,
    GENDER CHAR(3) CHECK(GENDER IN ('남', '여')),
    AGE NUMBER,
    NICKNAME VARCHAR2(30) NOT NULL,
    EMAIL VARCHAR2(30) NOT NULL,
    PHONE VARCHAR2(20) NOT NULL,
    ADDRESS VARCHAR2(30),
    ENROLL_DATE DATE DEFAULT SYSDATE,
    STATUS CHAR(2) CHECK (STATUS IN ('Y', 'N')),
    QUIT_REASON VARCHAR2(50),
    SELF_INTRODUCTION VARCHAR2(1000)
    
);


COMMENT ON COLUMN MEMBER.MEM_NO IS '회원번호';
COMMENT ON COLUMN MEMBER.MEM_GRADE IS '등급코드';
COMMENT ON COLUMN MEMBER.MEM_ID IS '회원아이디';
COMMENT ON COLUMN MEMBER.MEM_PWD IS '비밀번호';
COMMENT ON COLUMN MEMBER.MEM_NAME IS '회원명';
COMMENT ON COLUMN MEMBER.GENDER IS '성별';
COMMENT ON COLUMN MEMBER.AGE IS '나이';
COMMENT ON COLUMN MEMBER.NICKNAME IS '닉네임';
COMMENT ON COLUMN MEMBER.EMAIL IS '이메일';
COMMENT ON COLUMN MEMBER.PHONE IS '전화번호';
COMMENT ON COLUMN MEMBER.ADDRESS IS '주소';
COMMENT ON COLUMN MEMBER.ENROLL_DATE IS '회원가입일';
COMMENT ON COLUMN MEMBER.STATUS IS '회원상태';
COMMENT ON COLUMN MEMBER.QUIT_REASON IS '탈퇴사유';
COMMENT ON COLUMN MEMBER.SELF_INTRODUCTION IS '자기소개';

CREATE TABLE MEMBER_GRADE(
    GRADE_CODE NUMBER PRIMARY KEY,
    GRADE_NAME VARCHAR2(20) NOT NULL
);
COMMENT ON COLUMN MEMBER_GRADE.GRADE_CODE IS '등급코드';
COMMENT ON COLUMN MEMBER_GRADE.GRADE_NAME IS '등급명';

CREATE TABLE REPORT(
    REPORT_NO NUMBER PRIMARY KEY,
    REPORTER NUMBER NOT NULL REFERENCES MEMBER(MEM_NO),
    SUSPECT NUMBER NOT NULL REFERENCES MEMBER(MEM_NO),
    REPORT_CONTENT VARCHAR2(100) NOT NULL,
    REPORT_DATE DATE DEFAULT SYSDATE,
    RESULT VARCHAR2(5)
);

COMMENT ON COLUMN REPORT.REPORT_NO IS '신고번호';
COMMENT ON COLUMN REPORT.REPORTER IS '신고자';
COMMENT ON COLUMN REPORT.SUSPECT IS '피신고자';
COMMENT ON COLUMN REPORT.REPORT_CONTENT IS '신고내용';
COMMENT ON COLUMN REPORT.REPORT_DATE IS '신고일자';
COMMENT ON COLUMN REPORT.RESULT IS '처리여부';

----------------------------------- 승준 테이블 ----------------------------------

CREATE 
 TABLE 
  QNA(
        QNA_NO NUMBER PRIMARY KEY
      , BOARD_TITLE VARCHAR2(80) NOT NULL
      , BOARD_CONTENT VARCHAR2(1000) NOT NULL
      , QNA_VIEWS NUMBER
      , CREATE_DATE DATE DEFAULT SYSDATE
      , STATUS CHAR(1) DEFAULT 'Y' CHECK(STATUS IN ('Y','N')) NOT NULL
      , OPEN CHAR(1) DEFAULT 'N' CHECK(OPEN IN ('Y','N')) NOT NULL
      , REPLY CHAR(1) DEFAULT 'N' CHECK(REPLY IN ('Y','N')) NOT NULL
      , BOARD_WRITER NUMBER NOT NULL
      );

COMMENT ON COLUMN QNA.QNA_NO IS '게시판번호';
COMMENT ON COLUMN QNA.BOARD_TITLE IS '게시글제목';
COMMENT ON COLUMN QNA.BOARD_CONTENT IS '게시글내용';
COMMENT ON COLUMN QNA.QNA_VIEWS IS '조회수';
COMMENT ON COLUMN QNA.CREATE_DATE IS '작성일';
COMMENT ON COLUMN QNA.STATUS IS '상태값(Y/N)';
COMMENT ON COLUMN QNA.OPEN IS '공개여부(Y/N)';
COMMENT ON COLUMN QNA.REPLY IS '답변여부(Y/N)';
COMMENT ON COLUMN QNA.BOARD_WRITER IS 'QnA작성자회원번호';
        
CREATE
 TABLE
   FAQ (
         FAQ_NO NUMBER PRIMARY KEY
       , FAQ_TITLE VARCHAR2(80) NOT NULL
       , FAQ_CONTENT VARCHAR2(1000) NOT NULL
       , STATUS CHAR(1) DEFAULT 'Y' CHECK(STATUS IN ('Y','N')) NOT NULL
       , FAQ_WRITER NUMBER REFERENCES MEMBER(MEM_NO) NOT NULL
       );

COMMENT ON COLUMN FAQ.FAQ_NO IS '게시글번호';
COMMENT ON COLUMN FAQ.FAQ_TITLE IS '게시글제목';
COMMENT ON COLUMN FAQ.FAQ_CONTENT IS '게시글내용';
COMMENT ON COLUMN FAQ.STATUS IS '상태값(Y/N)';
COMMENT ON COLUMN FAQ.FAQ_WRITER IS '자주묻는질문작성자';
       
CREATE
 TABLE
NOTICE (
         NOTICE_NO NUMBER PRIMARY KEY
       , NOTICE_TITLE VARCHAR2(80) NOT NULL
       , NOTICE_CONTENT VARCHAR2(1000) NOT NULL
       , NOTICE_VIEWS NUMBER
       , CREATE_DATE DATE DEFAULT SYSDATE NOT NULL
       , STATUS CHAR(1) DEFAULT 'Y' CHECK(STATUS IN ('Y','N')) NOT NULL
       , NOTICE_WRITER NUMBER NOT NULL
       );
       
COMMENT ON COLUMN NOTICE.NOTICE_NO IS '공지사항번호';
COMMENT ON COLUMN NOTICE.NOTICE_TITLE IS '공지사항제목'; 
COMMENT ON COLUMN NOTICE.NOTICE_CONTENT IS '공지사항내용'; 
COMMENT ON COLUMN NOTICE.NOTICE_VIEWS IS '조회수'; 
COMMENT ON COLUMN NOTICE.CREATE_DATE IS '작성일'; 
COMMENT ON COLUMN NOTICE.STATUS IS '상태값(Y/N)'; 
COMMENT ON COLUMN NOTICE.NOTICE_WRITER IS '공지사항작성자'; 

---------------------------------래언  테이블 ------------------------------------

-- FOOD CATEGORY 

CREATE TABLE FOOD_CATEGORY(
    CATEGORY_NO NUMBER PRIMARY KEY,
    CATEGORY_NAME VARCHAR2(20)
);

CREATE TABLE TV(
    TV_NO NUMBER PRIMARY KEY,
    TV_NAME VARCHAR2(50)
);

COMMENT ON COLUMN TV.TV_NO IS 'TV맛집 번호';
COMMENT ON COLUMN TV.TV_NAME IS 'TV맛집 이름';

COMMENT ON COLUMN FOOD_CATEGORY.CATEGORY_NO IS '카테고리번호';
COMMENT ON COLUMN FOOD_CATEGORY.CATEGORY_NAME IS '카테고리명(한,중,일,양)';

CREATE TABLE RESTAURANT(
    REST_NO NUMBER PRIMARY KEY,
    CATEGORY_NO NUMBER REFERENCES FOOD_CATEGORY,
    TV_NO NUMBER REFERENCES TV,
    REST_NAME VARCHAR2(30) NOT NULL,
    REST_ADDRESS VARCHAR2(120) NOT NULL,
    REST_PHONE VARCHAR2(20) NOT NULL,
    PARKING VARCHAR2(10),
    INTRO VARCHAR2(500),
    REST_VIEWS NUMBER DEFAULT 0 NOT NULL,
    STATUS VARCHAR2(10) DEFAULT 'N',
    CHECK (STATUS IN('Y','N'))
   
);

COMMENT ON COLUMN RESTAURANT.REST_NO IS '음식점 번호';
COMMENT ON COLUMN RESTAURANT.CATEGORY_NO IS '카테고리 번호';
COMMENT ON COLUMN RESTAURANT.TV_NO IS 'TV출현 맛집';
COMMENT ON COLUMN RESTAURANT.REST_NAME IS '음식점 이름';
COMMENT ON COLUMN RESTAURANT.REST_ADDRESS IS '음식점 주소';
COMMENT ON COLUMN RESTAURANT.REST_PHONE IS '음식점 전화번호';
COMMENT ON COLUMN RESTAURANT.PARKING IS '주소여부';
COMMENT ON COLUMN RESTAURANT.INTRO IS '식당소개';
COMMENT ON COLUMN RESTAURANT.REST_VIEWS IS '조회수';
COMMENT ON COLUMN RESTAURANT.STATUS IS '등록여부(Y/N)';


CREATE TABLE REVIEW(
    REVIEW_NO NUMBER PRIMARY KEY,
    REST_NO REFERENCES RESTAURANT(REST_NO),
    REVIEW_CONTENT VARCHAR2(300) NOT NULL,
    RATING NUMBER NOT NULL,
    REVIEW_DATE DATE DEFAULT SYSDATE,
    TASTE VARCHAR2(20) NOT NULL,
    MEM_NO REFERENCES MEMBER(MEM_NO)
);

COMMENT ON COLUMN REVIEW.REVIEW_NO IS '리뷰번호';
COMMENT ON COLUMN REVIEW.REVIEW_CONTENT IS '리뷰내용';
COMMENT ON COLUMN REVIEW.RATING IS '별점';
COMMENT ON COLUMN REVIEW.REVIEW_DATE IS '작성일';
COMMENT ON COLUMN REVIEW.TASTE IS '맛평가';
COMMENT ON COLUMN REVIEW.REST_NO IS '음식점번호';
COMMENT ON COLUMN REVIEW.REVIEW_NO IS '회원번호';

CREATE TABLE REVIEW_UP(
    REVIEW_NO NUMBER REFERENCES REVIEW(REVIEW_NO),
    MEM_NO NUMBER REFERENCES MEMBER(MEM_NO)
);

CREATE TABLE OPEN_TIME(
    REST_NO NUMBER REFERENCES RESTAURANT(REST_NO),
    OPENING_TIME VARCHAR2(30) NOT NULL,
    REST_TIME VARCHAR2(30),
    BREAK_TIME VARCHAR2(30)
);

COMMENT ON COLUMN OPEN_TIME.REST_NO IS '음식점 번호';
COMMENT ON COLUMN OPEN_TIME.OPENING_TIME IS '영업 시간';
COMMENT ON COLUMN OPEN_TIME.REST_TIME IS '휴무일';
COMMENT ON COLUMN OPEN_TIME.BREAK_TIME IS '브레이크 타임';



--------------------------------- 관우 테이블 ------------------------------------
-- 즐겨찾기

CREATE TABLE FAVORITES(
    MEM_NO NUMBER NOT NULL,
    REST_NO NUMBER NOT NULL
);

COMMENT ON COLUMN FAVORITES.MEM_NO IS '즐겨찾기 회원번호';
COMMENT ON COLUMN FAVORITES.REST_NO IS '즐겨찾기 음식점번호';

ALTER TABLE FAVORITES
ADD CONSTRAINT FK_MEMBER_NO
FOREIGN KEY (MEM_NO)
REFERENCES MEMBER (MEM_NO);



ALTER TABLE FAVORITES
ADD CONSTRAINT FK_REST_NO
FOREIGN KEY (REST_NO)
REFERENCES RESTAURANT (REST_NO);

-- 메뉴 MENU

CREATE TABLE MENU(
    REST_NO NUMBER NOT NULL,
    FILE_NO NUMBER,
    MENU VARCHAR2(30) NOT NULL,
    PRICE NUMBER NOT NULL,
    MENU_GRADE NUMBER NOT NULL
);

COMMENT ON COLUMN MENU.REST_NO IS '음식점번호';
COMMENT ON COLUMN MENU.FILE_NO IS '첨부파일번호';
COMMENT ON COLUMN MENU.MENU IS '메뉴명';
COMMENT ON COLUMN MENU.PRICE IS '메뉴가격';
COMMENT ON COLUMN MENU.MENU_GRADE IS '대표메뉴 순번';


-- ATTACHMENT

CREATE TABLE ATTACHMENT(
    FILE_NO NUMBER CONSTRAINT PK_FILE_NO PRIMARY KEY,
    REF_BNO NUMBER NOT NULL,
    ORIGIN_NAME VARCHAR2(500) NOT NULL,
    CHANGE_NAME VARCHAR2(500) NOT NULL,
    FILE_PATH VARCHAR2(1000) NOT NULL,
    UPLOAD_DATE DATE DEFAULT SYSDATE NOT NULL,
    STATUS VARCHAR2(1) CHECK(STATUS IN('Y','N')),
    CATEGORY VARCHAR2(10) CHECK(CATEGORY IN('REV','QNA','REST'))
);

COMMENT ON COLUMN ATTACHMENT.FILE_NO IS '파일번호';
COMMENT ON COLUMN ATTACHMENT.REF_BNO IS '참조게시글 번호';
COMMENT ON COLUMN ATTACHMENT.ORIGIN_NAME IS '파일원본명';
COMMENT ON COLUMN ATTACHMENT.CHANGE_NAME IS '파일수정명';
COMMENT ON COLUMN ATTACHMENT.FILE_PATH IS '저장폴더경로';
COMMENT ON COLUMN ATTACHMENT.UPLOAD_DATE IS '업로드일자';
COMMENT ON COLUMN ATTACHMENT.STATUS IS '상태';
COMMENT ON COLUMN ATTACHMENT.CATEGORY IS '게시판 구분자';

---------------------------------- 정묵 테이블 -----------------------------------
--------------  식당 수정 제안 관련  ------------------   

CREATE TABLE UPDATE_REST (
  UPDATE_NO NUMBER PRIMARY KEY,
  UPDATE_CONTENT VARCHAR2(200) NOT NULL,
  REST_NO NUMBER NOT NULL,
  FOREIGN KEY (REST_NO) REFERENCES RESTAURANT(REST_NO)
);

COMMENT ON COLUMN UPDATE_REST.UPDATE_NO IS '수정번호';
COMMENT ON COLUMN UPDATE_REST.UPDATE_CONTENT IS '수정내용';
COMMENT ON COLUMN UPDATE_REST.REST_NO IS '음식점번호';

--------------    비회원  관련      ------------------   

CREATE TABLE NO_MEMBER (
  REST_NO NUMBER NOT NULL,
  RECENT_REST VARCHAR2(30) NULL,
  FOREIGN KEY (REST_NO) REFERENCES RESTAURANT(REST_NO)
);

COMMENT ON COLUMN NO_MEMBER.REST_NO IS '음식점번호';
COMMENT ON COLUMN NO_MEMBER.RECENT_REST IS '최근조회한음식점';

--------------    사이트  관련      ------------------   

CREATE TABLE SITE_INFO (
  SITE_NAME VARCHAR2(20) NOT NULL,
  SUB_NAME VARCHAR2(100) NOT NULL
);

COMMENT ON COLUMN SITE_INFO.SITE_NAME IS '사이트명';
COMMENT ON COLUMN SITE_INFO.SUB_NAME IS '부제목';

------------------------------------- 시퀀스 -----------------------------------

CREATE SEQUENCE SEQ_NNO --공지사항 넘버
NOCACHE;

CREATE SEQUENCE SEQ_QNO --QnA 넘버
NOCACHE;

CREATE SEQUENCE SEQ_FAQNO -- FAQ 번호
NOCACHE;

CREATE SEQUENCE SEQ_MNO --회원 넘버
NOCACHE;

CREATE SEQUENCE SEQ_REPNO --리포트 넘버
NOCACHE;

CREATE SEQUENCE SEQ_GNO --회원등급 넘버
NOCACHE;

CREATE SEQUENCE SEQ_RESTNO --음식점 넘버
NOCACHE;

CREATE SEQUENCE SEQ_REVNO --리뷰 넘버
NOCACHE;

CREATE SEQUENCE SEQ_FNO --파일번호
NOCACHE;

CREATE SEQUENCE SEQ_CNO --음식 카테고리 번호
NOCACHE;

CREATE SEQUENCE SEQ_UNO --식당수정 넘버
NOCACHE;



COMMIT;