/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.78
 * Generated at: 2023-08-24 09:45:25 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/views/common/mainPage.jsp", Long.valueOf(1692870319327L));
    _jspx_dependants.put("/views/common/menubar.jsp", Long.valueOf(1692858612051L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>Document</title>\r\n");
      out.write("</head>\r\n");
      out.write("<style>\r\n");
      out.write("    div{box-sizing: border-box;}\r\n");
      out.write("\r\n");
      out.write("    .menubar-area{\r\n");
      out.write("        position: sticky;\r\n");
      out.write("        top: 0;\r\n");
      out.write("        height: 100px;\r\n");
      out.write("        width: 1100px;\r\n");
      out.write("        margin: auto;\r\n");
      out.write("        background-color: white;\r\n");
      out.write("        z-index: 5;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .logo-area>img{\r\n");
      out.write("        margin-left: 45px;\r\n");
      out.write("        max-width: 90%;\r\n");
      out.write("        max-height: 90%;\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    .logo-area, .searchbar-area, .member-area{\r\n");
      out.write("        height: 100px;\r\n");
      out.write("        float: left;\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    .logo-area, .member-area{width: 20%;}\r\n");
      out.write("\r\n");
      out.write("    .member-area a{\r\n");
      out.write("        text-decoration: none;\r\n");
      out.write("        color: black;\r\n");
      out.write("        line-height: 90px;\r\n");
      out.write("        margin: 20px;\r\n");
      out.write("        font-size: 12px;\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    .searchbar-area{\r\n");
      out.write("        width: 60%;\r\n");
      out.write("        position: relative;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .searchbar-area input[type=text]{\r\n");
      out.write("        border-radius: 200px;\r\n");
      out.write("        width: 400px;\r\n");
      out.write("        height: 40px;\r\n");
      out.write("        margin: 25px 50px;\r\n");
      out.write("        background-color: rgb(240, 240, 240);\r\n");
      out.write("        border-color: white;\r\n");
      out.write("        padding-right: 30px; \r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .searchbar-area button{\r\n");
      out.write("        position: absolute;\r\n");
      out.write("        top: 50%;\r\n");
      out.write("        right: 200px;\r\n");
      out.write("        transform: translateY(-60%);\r\n");
      out.write("        border: 0;\r\n");
      out.write("        cursor: pointer;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("<body>\r\n");
      out.write("    <div class=\"menubar-area\">\r\n");
      out.write("        <div class=\"logo-area\">\r\n");
      out.write("            <img src=\"resources/img/logo.png\">\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"searchbar-area\">\r\n");
      out.write("            <form action=\"\">\r\n");
      out.write("                <input type=\"text\" placeholder=\"     지역, 음식 또는 식당명을 입력해주세요. \" style=\"border: 0px;\">\r\n");
      out.write("                <button type=\"submit\"><img src=\"resources/img/searchIcon.png\"></button>\r\n");
      out.write("            </form>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"member-area\" align=\"center\">\r\n");
      out.write("            <a href=\"\">로그인</a>\r\n");
      out.write("            <a href=\"\">회원가입</a>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write('\r');
      out.write('\n');
      out.write('	');
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>Document</title>\r\n");
      out.write("    <link href=\"https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.8.1/slick.css\" rel=\"stylesheet\">\r\n");
      out.write("	<link href=\"https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.8.1/slick-theme.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"resources/css/mainbody.css\" rel=\"stylesheet\">\r\n");
      out.write("    \r\n");
      out.write("    <script src=\"https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js\"></script>\r\n");
      out.write("	<script src=\"https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.8.1/slick.js\"></script>\r\n");
      out.write("    <script>\r\n");
      out.write("        $(document).ready(function(){\r\n");
      out.write("	          $('.slick').slick({\r\n");
      out.write("                rows: 2,\r\n");
      out.write("                slidesToShow:2,\r\n");
      out.write("                slidesToScroll:2,\r\n");
      out.write("                dots: true,\r\n");
      out.write("	          }) \r\n");
      out.write("	       });\r\n");
      out.write("    </script>\r\n");
      out.write("</head>\r\n");
      out.write("<style>\r\n");
      out.write("    .header-area{\r\n");
      out.write("    position: relative;\r\n");
      out.write("    width: 100%;\r\n");
      out.write("    height: 15%;\r\n");
      out.write("    background-image: url(\"resources/img/pork-cutlet2.jpg\");\r\n");
      out.write("    background-size: cover;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("<body>\r\n");
      out.write("    <div class=\"outer\">\r\n");
      out.write("        <div class=\"navbar\" align=\"center\">\r\n");
      out.write("            <div class=\"menu\"><a href=\"\">HOME</a></div>\r\n");
      out.write("            <div class=\"menu\"><a href=\"\">공지사항</a></div>\r\n");
      out.write("            <div class=\"menu\"><a href=\"\">자주묻는 질문</a></div>\r\n");
      out.write("            <div class=\"menu\"><a href=\"\">Q&A</a></div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"header-area\">\r\n");
      out.write("            <div class=\"bg\">솔직한 리뷰, 믿을 수 있는 평점 <br> <b>이눔세끼</b> </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"best-area\">\r\n");
      out.write("            <h2>믿고 보는 맛집 리스트</h2>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"top-list slick slider\" id=\"wrapper\">\r\n");
      out.write("            <ul>\r\n");
      out.write("                <li class=\"fl\">\r\n");
      out.write("                    <a href=\"#해당 이미지 상세정보창\">\r\n");
      out.write("                        <figure class=\"top-list-info\">\r\n");
      out.write("                            <div>                              \r\n");
      out.write("                                <img src=\"resources/img/bibimbap.jpg\">\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <figcaption>\r\n");
      out.write("                                <div class=\"list-pic-comment\">\r\n");
      out.write("                                    <span>비빔맛 맛집 TOP 10</span>\r\n");
      out.write("                                    <p>\"이것은 한국의 혼\"</p>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </figcaption>\r\n");
      out.write("                        </figure>\r\n");
      out.write("                    </a>\r\n");
      out.write("                </li>\r\n");
      out.write("            </ul>\r\n");
      out.write("            <ul>\r\n");
      out.write("                <li class=\"fl\">\r\n");
      out.write("                    <a href=\"#해당 이미지 상세정보창\">\r\n");
      out.write("                        <figure class=\"top-list-info\">\r\n");
      out.write("                            <div>                              \r\n");
      out.write("                                <img src=\"resources/img/chinese.jpg\">\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <figcaption>\r\n");
      out.write("                                <div class=\"list-pic-comment\">\r\n");
      out.write("                                    <span class=\"title\">중식 맛집 TOP 5</span>\r\n");
      out.write("                                    <p>\"짜장면 짬뽕 난 짬짜면\"</p>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </figcaption>\r\n");
      out.write("                        </figure>\r\n");
      out.write("                    </a>\r\n");
      out.write("                </li>\r\n");
      out.write("            </ul>\r\n");
      out.write("            <ul>\r\n");
      out.write("                <li class=\"fl\">\r\n");
      out.write("                    <a href=\"#해당 이미지 상세정보창\">\r\n");
      out.write("                        <figure class=\"top-list-info\">\r\n");
      out.write("                            <div>                              \r\n");
      out.write("                                <img src=\"resources/img/cooking.jpg\">\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <figcaption>\r\n");
      out.write("                                <div class=\"list-pic-comment\">\r\n");
      out.write("                                    <span class=\"title\">김치찌개 맛집 TOP3</span>\r\n");
      out.write("                                    <p>\"스팸 돼지고기 꽁치\"</p>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </figcaption>\r\n");
      out.write("                        </figure>\r\n");
      out.write("                    </a>\r\n");
      out.write("                </li>\r\n");
      out.write("            </ul>\r\n");
      out.write("            <ul>\r\n");
      out.write("                <li class=\"fl\">\r\n");
      out.write("                    <a href=\"#해당 이미지 상세정보창\">\r\n");
      out.write("                        <figure class=\"top-list-info\">\r\n");
      out.write("                            <div>                              \r\n");
      out.write("                                <img src=\"resources/img/pasta.jpg\">\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <figcaption>\r\n");
      out.write("                                <div class=\"list-pic-comment\">\r\n");
      out.write("                                    <span class=\"title\">서양 국시 TOP 5</span>\r\n");
      out.write("                                    <p>\"난 토마토\"</p>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </figcaption>\r\n");
      out.write("                        </figure>\r\n");
      out.write("                    </a>\r\n");
      out.write("                </li>\r\n");
      out.write("            </ul>\r\n");
      out.write("            <ul>\r\n");
      out.write("                <li class=\"fl\">\r\n");
      out.write("                    <a href=\"#해당 이미지 상세정보창\">\r\n");
      out.write("                        <figure class=\"top-list-info\">\r\n");
      out.write("                            <div>                              \r\n");
      out.write("                                <img src=\"resources/img/ramen.jpg\">\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <figcaption>\r\n");
      out.write("                                <div class=\"list-pic-comment\">\r\n");
      out.write("                                    <span class=\"title\">라멘 맛집 TOP 5</span>\r\n");
      out.write("                                    <p>\"매장안에 원피스 피규어 필수\"</p>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </figcaption>\r\n");
      out.write("                        </figure>\r\n");
      out.write("                    </a>\r\n");
      out.write("                </li>\r\n");
      out.write("            </ul>\r\n");
      out.write("            <ul>\r\n");
      out.write("                <li class=\"fl\">\r\n");
      out.write("                    <a href=\"#해당 이미지 상세정보창\">\r\n");
      out.write("                        <figure class=\"top-list-info\">\r\n");
      out.write("                            <div>                              \r\n");
      out.write("                                <img src=\"resources/img/soup.jpg\">\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <figcaption>\r\n");
      out.write("                                <div class=\"list-pic-comment\">\r\n");
      out.write("                                    <span class=\"title\">분식 맛집 TOP 3</span>\r\n");
      out.write("                                    <p>\"라면 돈까스 김밥 국룰\"</p>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </figcaption>\r\n");
      out.write("                        </figure>\r\n");
      out.write("                    </a>\r\n");
      out.write("                </li>\r\n");
      out.write("            </ul>\r\n");
      out.write("            <ul>\r\n");
      out.write("                <li class=\"fl\">\r\n");
      out.write("                    <a href=\"#해당 이미지 상세정보창\">\r\n");
      out.write("                        <figure class=\"top-list-info\">\r\n");
      out.write("                            <div>                              \r\n");
      out.write("                                <img src=\"resources/img/tteokbokki.jpg\">\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <figcaption>\r\n");
      out.write("                                <div class=\"list-pic-comment\">\r\n");
      out.write("                                    <span class=\"title\">국밥류 TOP 3</span>\r\n");
      out.write("                                    <p>\"이 돈이면 국밥이 몇그릇..\"</p>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </figcaption>\r\n");
      out.write("                        </figure>\r\n");
      out.write("                    </a>\r\n");
      out.write("                </li>\r\n");
      out.write("            </ul>\r\n");
      out.write("            <ul>\r\n");
      out.write("                <li class=\"fl\">\r\n");
      out.write("                    <a href=\"#해당 이미지 상세정보창\">\r\n");
      out.write("                        <figure class=\"top-list-info\">\r\n");
      out.write("                            <div>                              \r\n");
      out.write("                                <img src=\"resources/img/pasta.jpg\">\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <figcaption>\r\n");
      out.write("                                <div class=\"list-pic-comment\">\r\n");
      out.write("                                    <span class=\"title\">한식 맛집 TOP 3</span>\r\n");
      out.write("                                    <p>\"주모 샤따내려\"</p>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </figcaption>\r\n");
      out.write("                        </figure>\r\n");
      out.write("                    </a>\r\n");
      out.write("                </li>\r\n");
      out.write("            </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("        <br>\r\n");
      out.write("        <hr>\r\n");
      out.write("        <section class=\"main_most_popular_restaurant\">\r\n");
      out.write("            <h2 id=\"editor-select\">에디터가 선정한 식당</h2>\r\n");
      out.write("            <div class=\"popular_restaurant_container\">\r\n");
      out.write("                <ul>\r\n");
      out.write("                    <li class=\"fl\">\r\n");
      out.write("                        <a href=\"#해당 이미지 상세정보창\">\r\n");
      out.write("                            <img src=\"resources/img/bibimbap.jpg\">\r\n");
      out.write("                                <div class=\"info\">\r\n");
      out.write("                                    <span class=\"title\">새마을 식당</span>\r\n");
      out.write("                                    <strong>3.8</strong>\r\n");
      out.write("                                    <p>서울 역삼동 - 고기 / 제육</p>\r\n");
      out.write("                                </div>\r\n");
      out.write("                        </a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li class=\"fl\">\r\n");
      out.write("                        <a href=\"#해당 이미지 상세정보창\">\r\n");
      out.write("                            <img src=\"resources/img/bibimbap.jpg\">\r\n");
      out.write("                                <div class=\"info\">\r\n");
      out.write("                                    <span class=\"title\">새마을 식당</span>\r\n");
      out.write("                                    <strong>3.8</strong>\r\n");
      out.write("                                    <p>서울 역삼동 - 고기 / 제육</p>\r\n");
      out.write("                                </div>\r\n");
      out.write("                        </a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li class=\"fl\">\r\n");
      out.write("                        <a href=\"#해당 이미지 상세정보창\">\r\n");
      out.write("                            <img src=\"resources/img/bibimbap.jpg\">\r\n");
      out.write("                                <div class=\"info\">\r\n");
      out.write("                                    <span class=\"title\">새마을 식당</span>\r\n");
      out.write("                                    <strong>3.8</strong>\r\n");
      out.write("                                    <p>서울 역삼동 - 고기 / 제육</p>\r\n");
      out.write("                                </div>\r\n");
      out.write("                        </a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                </ul>\r\n");
      out.write("                <ul>\r\n");
      out.write("                    <li class=\"fl\">\r\n");
      out.write("                        <a href=\"#해당 이미지 상세정보창\">\r\n");
      out.write("                            <img src=\"resources/img/bibimbap.jpg\">\r\n");
      out.write("                                <div class=\"info\">\r\n");
      out.write("                                    <span class=\"title\">새마을 식당</span>\r\n");
      out.write("                                    <strong>3.8</strong>\r\n");
      out.write("                                    <p>서울 역삼동 - 고기 / 제육</p>\r\n");
      out.write("                                </div>\r\n");
      out.write("                        </a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li class=\"fl\">\r\n");
      out.write("                        <a href=\"#해당 이미지 상세정보창\">\r\n");
      out.write("                            <img src=\"resources/img/bibimbap.jpg\">\r\n");
      out.write("                                <div class=\"info\">\r\n");
      out.write("                                    <span class=\"title\">새마을 식당</span>\r\n");
      out.write("                                    <strong>3.8</strong>\r\n");
      out.write("                                    <p>서울 역삼동 - 고기 / 제육</p>\r\n");
      out.write("                                </div>\r\n");
      out.write("                        </a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li class=\"fl\">\r\n");
      out.write("                        <a href=\"#해당 이미지 상세정보창\">\r\n");
      out.write("                            <img src=\"resources/img/bibimbap.jpg\">\r\n");
      out.write("                                <div class=\"info\">\r\n");
      out.write("                                    <span class=\"title\">새마을 식당</span>\r\n");
      out.write("                                    <strong>3.8</strong>\r\n");
      out.write("                                    <p>서울 역삼동 - 고기 / 제육</p>\r\n");
      out.write("                                </div>\r\n");
      out.write("                        </a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("        </section>\r\n");
      out.write("       <hr>\r\n");
      out.write("       <section class=\"main_most_popular_restaurant\">\r\n");
      out.write("        <h2 id=\"editor-select\">지금 날씨에 먹기좋은 음식</h2>\r\n");
      out.write("        <div class=\"popular_restaurant_container\">\r\n");
      out.write("            <ul>\r\n");
      out.write("                <li class=\"fl\">\r\n");
      out.write("                    <a href=\"#해당 이미지 상세정보창\">\r\n");
      out.write("                        <img src=\"resources/img/bibimbap.jpg\">\r\n");
      out.write("                            <div class=\"info\">\r\n");
      out.write("                                <span class=\"title\">새마을 식당</span>\r\n");
      out.write("                                <strong>3.8</strong>\r\n");
      out.write("                                <p>서울 역삼동 - 고기 / 제육</p>\r\n");
      out.write("                            </div>\r\n");
      out.write("                    </a>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li class=\"fl\">\r\n");
      out.write("                    <a href=\"#해당 이미지 상세정보창\">\r\n");
      out.write("                        <img src=\"resources/img/bibimbap.jpg\">\r\n");
      out.write("                            <div class=\"info\">\r\n");
      out.write("                                <span class=\"title\">새마을 식당</span>\r\n");
      out.write("                                <strong>3.8</strong>\r\n");
      out.write("                                <p>서울 역삼동 - 고기 / 제육</p>\r\n");
      out.write("                            </div>\r\n");
      out.write("                    </a>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li class=\"fl\">\r\n");
      out.write("                    <a href=\"#해당 이미지 상세정보창\">\r\n");
      out.write("                        <img src=\"resources/img/bibimbap.jpg\">\r\n");
      out.write("                            <div class=\"info\">\r\n");
      out.write("                                <span class=\"title\">새마을 식당</span>\r\n");
      out.write("                                <strong>3.8</strong>\r\n");
      out.write("                                <p>서울 역삼동 - 고기 / 제육</p>\r\n");
      out.write("                            </div>\r\n");
      out.write("                    </a>\r\n");
      out.write("                </li>\r\n");
      out.write("            </ul>\r\n");
      out.write("            <ul>\r\n");
      out.write("                <li class=\"fl\">\r\n");
      out.write("                    <a href=\"#해당 이미지 상세정보창\">\r\n");
      out.write("                        <img src=\"resources/img/bibimbap.jpg\">\r\n");
      out.write("                            <div class=\"info\">\r\n");
      out.write("                                <span class=\"title\">새마을 식당</span>\r\n");
      out.write("                                <strong>3.8</strong>\r\n");
      out.write("                                <p>서울 역삼동 - 고기 / 제육</p>\r\n");
      out.write("                            </div>\r\n");
      out.write("                    </a>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li class=\"fl\">\r\n");
      out.write("                    <a href=\"#해당 이미지 상세정보창\">\r\n");
      out.write("                        <img src=\"resources/img/bibimbap.jpg\">\r\n");
      out.write("                            <div class=\"info\">\r\n");
      out.write("                                <span class=\"title\">새마을 식당</span>\r\n");
      out.write("                                <strong>3.8</strong>\r\n");
      out.write("                                <p>서울 역삼동 - 고기 / 제육</p>\r\n");
      out.write("                            </div>\r\n");
      out.write("                    </a>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li class=\"fl\">\r\n");
      out.write("                    <a href=\"#해당 이미지 상세정보창\">\r\n");
      out.write("                        <img src=\"resources/img/bibimbap.jpg\">\r\n");
      out.write("                            <div class=\"info\">\r\n");
      out.write("                                <span class=\"title\">새마을 식당</span>\r\n");
      out.write("                                <strong>3.8</strong>\r\n");
      out.write("                                <p>서울 역삼동 - 고기 / 제육</p>\r\n");
      out.write("                            </div>\r\n");
      out.write("                    </a>\r\n");
      out.write("                </li>\r\n");
      out.write("            </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("    </section>\r\n");
      out.write("    <hr>\r\n");
      out.write("    <section class=\"main_most_popular_restaurant\">\r\n");
      out.write("        <h2 id=\"editor-select\">점메추</h2>\r\n");
      out.write("        <div class=\"popular_restaurant_container\">\r\n");
      out.write("            <ul>\r\n");
      out.write("                <li class=\"fl\">\r\n");
      out.write("                     <figure class=\"restaurant-item\">\r\n");
      out.write("                         <div>                              \r\n");
      out.write("                   			 <a href=\"#해당 이미지 상세정보창\">\r\n");
      out.write("                             <img class=\"restaurant-item-image\" src=\"resources/img/bibimbap.jpg\">\r\n");
      out.write("                             </a>\r\n");
      out.write("                         </div>\r\n");
      out.write("                         <figcaption>\r\n");
      out.write("                             <div class=\"info tv_info\">\r\n");
      out.write("                                 <span class=\"title\">뭐시구 top 10</span>\r\n");
      out.write("                                 <p>\"뭐시구 뭐시구 뭐시구 뭐시구\"</p>\r\n");
      out.write("                             </div>\r\n");
      out.write("                         </figcaption>\r\n");
      out.write("                     </figure> \r\n");
      out.write("                </li>\r\n");
      out.write("                <li class=\"fl\">\r\n");
      out.write("                    <figure class=\"restaurant-item\">\r\n");
      out.write("                        <div>                              \r\n");
      out.write("                   			<a href=\"#해당 이미지 상세정보창\">\r\n");
      out.write("                            <img src=\"resources/img/bibimbap.jpg\">\r\n");
      out.write("                            </a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <figcaption>\r\n");
      out.write("                            <div class=\"info tv_info\">\r\n");
      out.write("                                <span class=\"title\">뭐시구 top 10</span>\r\n");
      out.write("                                <p>\"뭐시구 뭐시구 뭐시구 뭐시구\"</p>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </figcaption>\r\n");
      out.write("                    </figure>\r\n");
      out.write("                </li>\r\n");
      out.write("            </ul>\r\n");
      out.write("            <ul>\r\n");
      out.write("                <li class=\"fl\">\r\n");
      out.write("                    <figure class=\"restaurant-item\">\r\n");
      out.write("                        <div>                              \r\n");
      out.write("                			<a href=\"#해당 이미지 상세정보창\">\r\n");
      out.write("                            <img src=\"resources/img/bibimbap.jpg\">\r\n");
      out.write("                            </a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <figcaption>\r\n");
      out.write("                            <div class=\"info tv_info\">\r\n");
      out.write("                                <span class=\"title\">뭐시구 top 10</span>\r\n");
      out.write("                                <p>\"뭐시구 뭐시구 뭐시구 뭐시구\"</p>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </figcaption>\r\n");
      out.write("                    </figure>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li class=\"fl\">\r\n");
      out.write("                    <figure class=\"restaurant-item\">\r\n");
      out.write("                        <div>                              \r\n");
      out.write("              			    <a href=\"#해당 이미지 상세정보창\">\r\n");
      out.write("                            <img src=\"resources/img/bibimbap.jpg\">\r\n");
      out.write("                            </a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <figcaption>\r\n");
      out.write("                            <div class=\"info tv_info\">\r\n");
      out.write("                                <span class=\"title\">뭐시구 top 10</span>\r\n");
      out.write("                                <p>\"뭐시구 뭐시구 뭐시구 뭐시구\"</p>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </figcaption>\r\n");
      out.write("                    </figure>\r\n");
      out.write("                </li>\r\n");
      out.write("            </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("    </section>\r\n");
      out.write("    </div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
